version: '3.8'

services:
  nginx:
    image: nginx:1.19.8
    container_name: nginx
    ports:
      - "90:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html

  web:
    build:
      context: .
    container_name: web
    ports:
     - "81:80"
    volumes:
      - ./web1/:/var/www/html

  web2:
    build:
      context: .
    container_name: web2
    ports:
     - "82:80"
    volumes:
      - ./web2/:/var/www/html

  web3:
    build:
      context: .
    container_name: web3
    ports:
     - "83:80"
    volumes:
      - ./web3/:/var/www/html